// Ticket numbers themselves are generated by the database (a Postgres
// IDENTITY column on `tickets.ticket_number` — see
// src/db/schema/tickets.ts), never by record counts, timestamps, random
// values, or client-side logic, so they stay unique and sequential even
// under concurrent inserts. This module only formats an already-assigned
// number for consistent, human-friendly display.

const TICKET_NUMBER_PREFIX = "TKT-";
const TICKET_NUMBER_DIGITS = 6;

export function formatTicketNumber(ticketNumber: number): string {
  return `${TICKET_NUMBER_PREFIX}${String(ticketNumber).padStart(TICKET_NUMBER_DIGITS, "0")}`;
}
